eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://cloud-eureka-server:8761/eureka/  for docker container
server:
  port: 8762
spring:
  application:
    name: service-hi