version: '3'
services:
  cloud-eureka-server:
    image: com.zhou/cloud-eureka-server
    restart: always
    ports:
      - 8761:8761

  cloud-eureka-client:
    image: com.zhou/cloud-eureka-client
    restart: always
    ports:
      - 8762:8762
